extends:
  - '@glevanov/eslint-config'
  - '@glevanov/eslint-config/typescript'
  - '@glevanov/eslint-config/react'
rules:
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
